### ISSUE TITLE
v 1.1.0 signs not saving in multiplayer

### ISSUE THREAD

**Issue by volf78** [move123456789/SOTF-Mods#1]
Using Redloader 0.81. Sings otherwise seem to work fine when hosting a game but when exiting a game and reentering the sign is gone. Only tested in multiplayer.

**Comment by move123456789** [comment]
The issue should be resolved in the new RedLoader release 0.8.2

**Comment by volf78** [comment]
The issue still persists with 0.8.2, also having a save issue with buildshare where buildings arent saved

**Comment by move123456789** [comment]
Okay maybe the RedLoader in game saving system is not updated yet. Can look into it when i have time

**Comment by move123456789** [comment]
Do you save your game after you have placed out signs? If so can you provide any logs, would be very useful. Also go in mods settings for Signs and enable all the logs before testing again.

**Comment by volf78** [comment]
Google drive link yo the latest log after starting a game - making a sign - put the
sign on the wall - saved - reloaded and the sign is gone.

[https://drive.google.com/file/d/1T0MiUCtgh18Oh_TRb4k3wED0bJ3mXJCg/view?usp=sharing](url)

**Comment by move123456789** [comment]
Okay thanks, i will look into it

**Comment by move123456789** [comment]
Issue should be solved in this release: [RedLoader v0.8.3 updated](https://github.com/ToniMacaroni/RedLoader/releases/tag/0.8.3)

**Comment by volf78** [comment]
Sadly Redloader update didn't solve the issue, still signs do not get saved. The only difference was in 2 out of 3 tests i got stuck in inventory after crafting a sign.

**Comment by move123456789** [comment]
Hmm, not good. Can you try to create a new world and place a sign, then save and then rejoin and see if it works in that case. 


It seems like there is some issue with redloader

**Comment by volf78** [comment]
Tested with new world single player no other mods installed - made sign attached to a tree this time saved reloaded and the sign was gone. 
Might indeed be a redloader issue, ill test again when a new version is released.

**Comment by move123456789** [comment]
I have started updating this mod to, to work around that

**Comment by move123456789** [comment]
The mod is now updated and should work fine now
